FROM golang:alpine AS builder

WORKDIR $GOROOT/src/github.com/Brijeshlakkad/delinkcious/svc/link_service
ADD ./main.go main.go
ADD ./service service

RUN go mod init link_service

# Fetch dependencies
RUN go get

RUN CGO_ENABLED=0 GOOS=linux go build -o /link_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/link_service"]