FROM brijeshlakkad/delinkcious-python-flask-grpc:0.1
MAINTAINER Brijesh Lakkad "brijeshlakkad22@gmail.com"
COPY . /api_gateway_service
WORKDIR /api_gateway_service
EXPOSE 5000
ENTRYPOINT python run.py
